package com.careconnect360.notification.enums;

public enum NotificationType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED,
    CLAIM_SUBMITTED,
    CLAIM_VERIFIED,
    CLAIM_APPROVED,
    CLAIM_REJECTED,
    CLAIM_PAID,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    APPOINTMENT,
    INSURANCE_POLICY,
    CLAIM,
    PAYMENT,
    SYSTEM
}