CREATE DATABASE IF NOT EXISTS careconnect360
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'careconnect'@'localhost'
  IDENTIFIED BY '<LOCAL_DB_PASSWORD>';

GRANT ALL PRIVILEGES ON careconnect360.* TO 'careconnect'@'localhost';
FLUSH PRIVILEGES;
